project:
  type: website
  output-dir: docs

website:
  title: "quarto2"
  search: false
  navbar:
    background: white
    title: false
    collapse: false
    logo: mlogo2.png
    right:
      # - posts/html-test/index.qmd
      - posts/illustration/index.qmd
      - posts.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
  page-footer: 
    center: "© 2023 Manifest AI" 
format:
  html:
    # max-width: 206px doesn't do anything
    fontsize: 14px
    # backgroundcolor: red
    theme:
      light: 
        - flatly
        - custom1.scss
      # dark: darkly
      
    grid:
      # sidebar-width: 300px
      body-width: 576px
      # margin-width: 300px
      # gutter-width: 1.5rem
    css: styles.css



